export const FETCH_STATUS_START = 'FETCH_STATUS_START';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAILED = 'FETCH_STATUS_FAILED';

export const FETCH_WO_START = 'FETCH_WO_START';
export const FETCH_WO_SUCCESS = 'FETCH_WO_SUCCESS';
export const FETCH_WO_FAILED = 'FETCH_WO_FAILED';

export const TOGGLE_TASK_ACTIONS = 'TOGGLE_TASK_ACTIONS';

export const TOGGLE_WO_MODAL = 'TOGGLE_WO_MODAL';