export const FETCH_STATUS_START = 'FETCH_STATUS_START';
export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_FAILED = 'FETCH_STATUS_FAILED';

export const FETCH_WO_START = 'FETCH_WO_START';
export const FETCH_WO_SUCCESS = 'FETCH_WO_SUCCESS';
export const FETCH_WO_FAILED = 'FETCH_WO_FAILED';

export const TOGGLE_TASK_ACTIONS = 'TOGGLE_TASK_ACTIONS';

export const TOGGLE_WO_MODAL = 'TOGGLE_WO_MODAL';
export const FORM_ELEMENT_CHANGE = 'FORM_ELEMENT_CHANGE';
export const FILTER_ELEMENT_CHANGE = 'FILTER_ELEMENT_CHANGE';
export const UPDATE_WO_START = 'UPDATE_WO_START';
export const UPDATE_WO_FAIL = 'UPDATE_WO_FAIL';
export const UPDATE_WO_SUCCESS = 'UPDATE_WO_SUCCESS';
export const UPDATE_WO_LIST = 'UPDATE_WO_LIST';
export const APPLY_FILTER_TO_WO_LIST = 'APPLY_FILTER_TO_WO_LIST';
export const FILTER_CUSTOMERS_ON_PROJECT_SELECT = 'FILTER_CUSTOMERS_ON_PROJECT_SELECT';
export const FILTER_PROJECTS_ON_CUSTOMER_SELECT = 'FILTER_PROJECTS_ON_CUSTOMER_SELECT';
export const DRAG_WO_CHANGE_STATUS = 'DRAG_WO_CHANGE_STATUS';
export const SEARCH_WORKING_ORDER_BOARD = 'SEARCH_WORKING_ORDER_BOARD';

export const FETCH_PROJECT_START = 'FETCH_PROJECT_START';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
export const FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL';
export const FETCH_PROJECT_WO_START = 'FETCH_PROJECT_WO_START';
export const FETCH_PROJECT_WO_SUCCESS = 'FETCH_PROJECT_WO_SUCCESS';
export const FETCH_PROJECT_WO_FAIL = 'FETCH_PROJECT_WO_FAIL';
export const DRAG_PROJECT_WO_CHANGE_STATUS = 'DRAG_PROJECT_WO_CHANGE_STATUS';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_PROJECT_STATUS_START = 'FETCH_PROJECT_STATUS_START';
export const FETCH_PROJECT_STATUS_SUCCESS = 'FETCH_PROJECT_STATUS_SUCCESS';
export const FETCH_PROJECT_STATUS_FAILED = 'FETCH_PROJECT_STATUS_FAILED';
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';

export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAIL = 'FETCH_EMPLOYEES_FAIL';